### ISSUE TITLE
Forced https

### ISSUE THREAD

**Issue by mathus13** [mix86/SublimeJira#8]
Having an issue with forced https:
My Jira URL is behind a firewall and not using https. The plugin seems to be forcing https and failing

```
reloading plugin Jira.__init__
reloading plugin Jira.conf
reloading plugin Jira.issue
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 73, in reload_plugin   m = importlib.import_module(modulename)
  File "X/importlib/__init__.py", line 88, in import_module
  File "<frozen importlib._bootstrap>", line 1577, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1558, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1525, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 586, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1023, in load_module
  File "<frozen importlib._bootstrap>", line 1004, in load_module
  File "<frozen importlib._bootstrap>", line 562, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 869, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "/home/shawn/.config/sublime-text-3/Packages/Jira/issue.py", line 5, in <module>
    from jira.client import JIRA
  File "/home/shawn/.config/sublime-text-3/Packages/Jira/lib/jira/__init__.py", line 4, in <module>
    from .config import get_jira
  File "/home/shawn/.config/sublime-text-3/Packages/Jira/lib/jira/config.py", line 17, in <module>
    from jira.client import JIRA
  File "/home/shawn/.config/sublime-text-3/Packages/Jira/lib/jira/client.py", line 20, in <module>
    import requests
  File "/home/shawn/.config/sublime-text-3/Packages/Jira/lib/requests/__init__.py", line 58, in <module>
    from . import utils
  File "/home/shawn/.config/sublime-text-3/Packages/Jira/lib/requests/utils.py", line 23, in <module>
    from .compat import parse_http_list as _parse_list_header
  File "/home/shawn/.config/sublime-text-3/Packages/Jira/lib/requests/compat.py", line 7, in <module>
    from .packages import charade as chardet
  File "/home/shawn/.config/sublime-text-3/Packages/Jira/lib/requests/packages/__init__.py", line 3, in <module>
    from . import urllib3
  File "/home/shawn/.config/sublime-text-3/Packages/Jira/lib/requests/packages/urllib3/__init__.py", line 16, in <module>
    from .connectionpool import (
  File "/home/shawn/.config/sublime-text-3/Packages/Jira/lib/requests/packages/urllib3/connectionpool.py", line 31, in <module>
    from .packages.ssl_match_hostname import CertificateError
  File "/home/shawn/.config/sublime-text-3/Packages/Jira/lib/requests/packages/urllib3/packages/__init__.py", line 3, in <module>
    from . import ssl_match_hostname
ImportError: cannot import name ssl_match_hostname
```

**Comment by sirbabyface** [comment]
This is also happening to me.
